name: glslgen
description: Small package to generate type safe uniform bindings for flutter fragment shaders.
version: 0.1.0
homepage: https://github.com/HrX03/glslgen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  antlr4: ^4.13.0
  build: ^2.4.0
  code_builder: ^4.5.0
  dart_style: ^2.3.1
  flutter:
    sdk: flutter
  path: ^1.8.3
  pubspec_parse: ^1.2.3
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter: